# Generated by Django 3.0.3 on 2020-02-04 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_box', '0002_auto_20200204_0139'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='byline',
            new_name='bio',
        ),
    ]
