# Generated by Django 3.0.3 on 2020-02-04 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_box', '0003_auto_20200204_0139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='bio',
            field=models.TextField(),
        ),
    ]
